services:
  - type: web
    name: myers-cybersecurity
    env: docker
    repo: https://github.com/YOUR_USERNAME/myersdigitalservicesAI
    branch: main
    plan: free
    autoDeploy: true
    envVars:
      - key: ENVIRONMENT
        value: production
      - key: DOMAIN
        value: https://myers-cybersecurity.onrender.com

