services:
  - type: web
    name: myers-cybersecurity
    env: docker
    repo: https://github.com/myersdigitalservicesai/myersdigitalservicesAI # This should be your repository
    branch: main
    plan: free # Or your desired plan
    autoDeploy: true
    healthCheckPath: /healthz # CORRECTED: Was /health
    envVars:
      - key: ENVIRONMENT
        value: production
      - key: DOMAIN
        value: https://myers-cybersecurity.onrender.com # This will be your app's domain
      - key: DATABASE_URL
        fromDatabase:
          name: myers-db # Assuming you name your Render database this
          property: connectionString
      - key: STRIPE_SECRET_KEY
        sync: false
      - key: STRIPE_WEBHOOK_SECRET
        sync: false
      - key: SMTP_API_KEY
        sync: false
      - key: SMTP_SERVER
        sync: false
      - key: SMTP_PORT
        sync: false
      - key: SMTP_USER
        sync: false
      - key: SENDER_EMAIL
        sync: false
      - key: APP_URL
        value: https://myers-cybersecurity.onrender.com # This will be your app's domain
      - key: SETUP_ADMIN_EMAIL
        sync: false
      - key: CORS_ALLOWED_ORIGINS
        value: "https://myers-cybersecurity.onrender.com" # Your frontend URL
      - key: TOKEN_URL_PATH
        value: "token" # The path for your token endpoint

# Example of a database to link with the service
databases:
  - name: myers-db
    databaseName: myers_cybersecurity
    user: myers_user
    plan: free # Or your desired plan
