# render.yaml
# This file defines the "Infrastructure as Code" for the MyersCybersecurity platform on Render.
# It sets up a single Docker service and a corresponding PostgreSQL database.

services:
  - type: web
    name: myers-cybersecurity
    env: docker
    repo: https://github.com/myersdigitalservicesai/myers-cybersecurity-platform # Ensure this is your repository URL
    branch: main
    plan: starter # Or your desired plan
    autoDeploy: true
    healthCheckPath: /healthz
    envVars:
      - key: ENVIRONMENT
        value: production
      - key: DATABASE_URL
        fromDatabase:
          name: myers-cybersecurity-db
          property: connectionString
      - key: APP_URL
        fromService:
          type: web
          name: myers-cybersecurity
          property: url
      - key: CORS_ALLOWED_ORIGINS
        fromService:
          type: web
          name: myers-cybersecurity
          property: url
      - key: TOKEN_URL_PATH
        value: "token"
      # --- SECRETS ---
      # These keys must be set in your Render Environment Group
      # and will not be synced from this file.
      - key: JWT_SECRET_KEY
        sync: false
      - key: ENCRYPTION_KEY
        sync: false
      - key: STRIPE_SECRET_KEY
        sync: false
      - key: STRIPE_WEBHOOK_SECRET
        sync: false
      - key: SMTP_API_KEY
        sync: false
      - key: SETUP_ADMIN_EMAIL
        sync: false

# Defines the PostgreSQL database linked to the service above
databases:
  - name: myers-cybersecurity-db
    databaseName: myers_cybersecurity
    user: myers_user
    plan: starter # Or your desired plan
