name: Sync Render Secrets

on:
  workflow_dispatch:  # Manual trigger only

jobs:
  sync:
    runs-on: ubuntu-latest

    steps:
      - name: Sync secrets to Render
        run: |
          set -e
          API_URL="https://api.render.com/v1/services/${{ secrets.RENDER_SERVICE_ID }}/env-vars"
          AUTH_HEADER="Authorization: Bearer ${{ secrets.RENDER_API_KEY }}"

          echo "Syncing secrets to Render..."
          response=$(curl -s -w "%{http_code}" -o response.txt -X PATCH "$API_URL" \
            -H "$AUTH_HEADER" \
            -H "Content-Type: application/json" \
            -d '{
              "envVars": [
                {"key": "SUPABASE_URL", "value": "'"${{ secrets.SUPABASE_URL }}"'"},
                {"key": "SUPABASE_KEY", "value": "'"${{ secrets.SUPABASE_KEY }}"'"},
                {"key": "SENDGRID_API_KEY", "value": "'"${{ secrets.SENDGRID_API_KEY }}"'"},
                {"key": "EMAIL_SENDER", "value": "'"${{ secrets.EMAIL_SENDER }}"'"}
              ]
            }')
          if [ "$response" != "200" ]; then
            echo "Failed to sync secrets to Render. Response code: $response"
            cat response.txt
            exit 1
          fi
          echo "Secrets synced to Render successfully."
