name: Sync Render Secrets

on:
  workflow_dispatch:  # Manual trigger only

jobs:
  sync:
    runs-on: ubuntu-latest

    steps:
      - name: Sync secrets to Render
        run: |
          API_URL="https://api.render.com/v1/services/${{ secrets.RENDER_SERVICE_ID }}/env-vars"
          AUTH_HEADER="Authorization: Bearer ${{ secrets.RENDER_API_KEY }}"

          curl -X PATCH "$API_URL" \
            -H "$AUTH_HEADER" \
            -H "Content-Type: application/json" \
            -d '{
              "envVars": [
                {"key": "SUPABASE_URL", "value": "'"${{ secrets.SUPABASE_URL }}"'"},
                {"key": "SUPABASE_KEY", "value": "'"${{ secrets.SUPABASE_KEY }}"'"},
                {"key": "SENDGRID_API_KEY", "value": "'"${{ secrets.SENDGRID_API_KEY }}"'"},
                {"key": "EMAIL_SENDER", "value": "'"${{ secrets.EMAIL_SENDER }}"'"}
              ]
            }'
